id: 2git_edit_readme
learningObjectives: 
- Commit git changes
hints:
startFlow:
  do:
  - actionId: bot_message
    params:
      person: lucca
      messages:
      - text: "Now that we've created a new branch, we're ready to change some files!"
      - text: "We need a README.md file in your repository with some content. Copy the text below and paste it into the newly created file." 
      - text: |
          ```
            # Congrats on your new README file! 
            ![Alt text](https://i.giphy.com/L0O3TQpp0WnSXmxV8p.gif)
            # [Let's go!](https://app.wilco.gg/chat/lucca)
          ```
      - text: "![](${newreadmefile.png})"
      - text: ":instruction[Create a README file] and [copy/paste the text](${user.repository}/new/${user.properties.branchname}/?filename=README.md)"
  - actionId: bot_message
    params:
      person: lucca
      messages:
      - text: "Once you are done editing, :instruction[click Commit Changes]"
      - text: "I'll check when you have committed the change so we can move forward."
trigger:
  type: github_push
  flowNode:
    if:
      conditions:
      - conditionId: github_is_file_added_in_push
        params:
          defaultResult: false
          fileName: README.md
      then:
        do:
        - actionId: bot_message
          params:
            person: lucca
            messages:
            - text: "Perfect execution! Well done. You've committed your first change! Does it feel great?"
        - actionId: bot_message
          params:
            person: lucca
            messages:
            - text: "You've just learned how to create a branch, add a README.md, and commit changes—great start!"
            - text: "Next, learn how to collaborate using pull requests. It's the key to sharing code, getting feedback, and merging updates safely."
            - text: "👉 Check out the \"Pull Requests\" module on [GitHub Skills](https://github.com/skills/review-pull-requests/) to practice proposing changes and collaborating like a pro."
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: lucca
            messages:
            - text: "Hmm, I see you pushed some changes to a new branch, but it seems **you forgot to edit the `README.md` file**"
              delay: 2500
